[build]
builder = "NIXPACKS"
watchPatterns = ["apega-backend/**", "apega-mobile/**"]

[deploy]
startCommand = "cd apega-backend && node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
